api = 1
name = "make-build"
version = "0.1.0"
description = "Compila con make cada carpeta que tenga un Makefile"
requires = ["make"]

[type]
scanned = true
detect = ["**/Makefile"]
command = "make"
dry_run = "make --dry-run"
